version: "3"
services:
  zkcream-ipfs:
    container_name: zkcream-ipfs
    build: ./ipfs
    ports:
      - "5001:5001" # api
    restart: always

  # zkcream-geth:
  #   container_name: zkcream-geth
  #   build: ./geth
  #   ports:
  #     - "8545:8545"
  #     - "8546:8546"
  #   restart: always